As a Data Analyst at a leading global HR consultancy, your mission is to delve into an extensive database of resumes to identify suitable candidates for tech-focused roles. This task involves using regular expressions to extract key data points and applying data preprocessing techniques to organize this information effectively.

### Dataset Summary

`resumes.csv`

| Column      | Data Type | Description                                                  |
|-------------|-----------|--------------------------------------------------------------|
| `ID`        | float     | Unique identifier for each resume.                           |
| `Resume_str`| object    | Full text of the resume, rich with details for analysis.     |
| `Category`  | object    | Job category of the resume, indicating the field of expertise. |


### Apply your regular expressions and data preprocessing skills to efficiently organize resumes data.

### Generate a new DataFrame named candidates_df containing the following columns:
+ **id**: Candidate ID.
+ **job_title**: Most recent job title.
+ **tech_skills**: List of technical skills that may include Python, SQL, R, and Excel.
+ **education**: Highest educational degree such as PhD, Master, or Bachelor.

In [47]:
import pandas as pd
import re

# Load the resume dataset from a CSV file into a DataFrame
resumes = pd.read_csv('resumes.csv')
def clean_text(text):    
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

resumes['Resume_str'] = resumes['Resume_str'].apply(clean_text)

In [40]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk import pos_tag, ne_chunk
import os

# Get the current working directory
current_directory = os.getcwd()
nltk.data.path.append(current_directory)

# Download necessary NLTK resources
nltk.download('punkt', download_dir=current_directory)
nltk.download('averaged_perceptron_tagger', download_dir=current_directory)
nltk.download('maxent_ne_chunker', download_dir=current_directory)
nltk.download('words', download_dir=current_directory)

[nltk_data] Downloading package punkt to d:\09_Project_2024\08_DataCam
[nltk_data]     p\00_projects\mmdt_data_projects\text_cleaning...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to d:\09_Pr
[nltk_data]     oject_2024\08_DataCamp\00_projects\mmdt_data_projects\
[nltk_data]     text_cleaning...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to d:\09_Project_202
[nltk_data]     4\08_DataCamp\00_projects\mmdt_data_projects\text_clea
[nltk_data]     ning...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to d:\09_Project_2024\08_DataCam
[nltk_data]     p\00_projects\mmdt_data_projects\text_cleaning...
[nltk_data]   Package words is already up-to-date!

True

In [48]:
job_title_pattern =r"^([A-Z\s\.\,\-]+)\b"
edu_pattern = r"(Bachelor's|Master's|PhD|Doctorate|Associate's|Education|degree|University)\s*(of|in)?\s*([A-Za-z\s\.\,\-]+)?(?:,|\bat\b)?\s*([A-Za-z\s\.]+)"
skill_pattern = r"\bskill\b\s+(.+)"
job_title = []
education = []
tech_skills = []

skill_keywords = {'python', 'java', 'machine learning', 'project management', 'data analysis', 'public speaking', 'leadership', 'communication'}

for resume_text in resumes['Resume_str']:
    job_titles_found = re.findall(job_title_pattern, resume_text)
    if len(job_titles_found)>0:
        job_title.append(job_titles_found[0])
    else:
        job_title.append(None)
 
 
    edu_found = re.findall(edu_pattern, resume_text, re.IGNORECASE)
    if len(edu_found)>0:
        education.append(edu_found[0][2])
    else:
        education.append(None)
    

candidates_df = pd.DataFrame({'id':resumes['ID'], 'job_title':job_title, 'education':education})
candidates_df

,id,job_title,education
0,16852973.0,HR ADMINISTRATORMARKETING ASSOCIATE HR ADMINIS...,NA Business Administration Jefferson College C...
1,22323967.0,HR SPECIALIST US HR OPERATIONS,Master of Arts Corporate Communication Public ...
2,33176873.0,HR DIRECTOR,Presidents Honor Roll Friends University Deans...
3,27018550.0,HR SPECIALIST,and Training Certificate of Completion Busines...
4,17812897.0,HR MANAGER,Bachelor of Business Administration MOUNT VERN...
...,...,...,...
1347,30311202.0,RM,and Training Curtis Senior High School City St...
1348,11121498.0,CHEF,Associate of Arts Culinary Arts Culinary Insti...
1349,32518109.0,CHEF,and Training High School Diploma General Educa...
1350,26718039.0,CHEF,None
1351,23568731.0,CHEF,Associate of Applied Science Culinary Arts Hud...